import type { Event } from "../type/event";

export const mockEvents: Event[] = [
  {
    id: "1",
    title: "Community Garden Cleanup",
    description:
      "Join us for a morning of community service as we clean and beautify our local community garden. All ages welcome!",
    category: "community",
    date: "2024-01-20",
    time: "09:00",
    location: "Riverside Community Garden",
    address: "123 Garden St, Downtown",
    price: 0,
    maxAttendees: 50,
    currentAttendees: 23,
    imageUrl: "/placeholder.svg?height=200&width=300",
    organizer: {
      name: "Green City Initiative",
      email: "contact@greencity.org",
    },
    tags: ["volunteer", "environment", "community"],
    featured: true,
  },
  {
    id: "2",
    title: "Local Football Tournament",
    description:
      "Annual neighborhood football tournament. Teams of 5 players each. Prizes for winners and great fun for all!",
    category: "sports",
    date: "2024-01-22",
    time: "14:00",
    location: "Central Park Sports Field",
    address: "456 Park Ave, Central District",
    price: 15,
    maxAttendees: 80,
    currentAttendees: 67,
    imageUrl: "/placeholder.svg?height=200&width=300",
    organizer: {
      name: "Sports Club United",
      email: "info@sportsclub.com",
    },
    tags: ["football", "tournament", "competition"],
    featured: false,
  },
  {
    id: "3",
    title: "Pottery Making Workshop",
    description:
      "Learn the basics of pottery making in this hands-on workshop. All materials provided. Perfect for beginners!",
    category: "workshop",
    date: "2024-01-25",
    time: "18:30",
    location: "Creative Arts Studio",
    address: "789 Art Lane, Arts Quarter",
    price: 45,
    maxAttendees: 15,
    currentAttendees: 8,
    imageUrl: "/placeholder.svg?height=200&width=300",
    organizer: {
      name: "Sarah Chen",
      email: "sarah@creativestudio.com",
    },
    tags: ["pottery", "art", "hands-on", "beginner"],
    featured: true,
  },
  {
    id: "4",
    title: "Jazz Night at The Blue Note",
    description: "An evening of smooth jazz featuring local musicians. Great atmosphere, drinks, and music. 21+ event.",
    category: "concert",
    date: "2024-01-27",
    time: "20:00",
    location: "The Blue Note Cafe",
    address: "321 Music St, Entertainment District",
    price: 25,
    maxAttendees: 100,
    currentAttendees: 45,
    imageUrl: "/placeholder.svg?height=200&width=300",
    organizer: {
      name: "Blue Note Entertainment",
      email: "events@bluenote.com",
    },
    tags: ["jazz", "music", "nightlife", "21+"],
    featured: false,
  },
  {
    id: "5",
    title: "Shakespeare in the Park",
    description:
      "Free outdoor performance of Romeo and Juliet by the Community Theater Group. Bring blankets and enjoy!",
    category: "performance",
    date: "2024-01-28",
    time: "19:00",
    location: "Sunset Park Amphitheater",
    address: "654 Sunset Blvd, West Side",
    price: 0,
    maxAttendees: 200,
    currentAttendees: 89,
    imageUrl: "/placeholder.svg?height=200&width=300",
    organizer: {
      name: "Community Theater Group",
      email: "info@communitytheater.org",
    },
    tags: ["theater", "shakespeare", "free", "outdoor"],
    featured: true,
  },
  {
    id: "6",
    title: "Morning Yoga in the Park",
    description:
      "Start your day with peaceful yoga in beautiful natural surroundings. All skill levels welcome. Bring your own mat.",
    category: "sports",
    date: "2024-01-21",
    time: "07:00",
    location: "Harmony Park",
    address: "987 Zen Way, Peaceful District",
    price: 12,
    maxAttendees: 30,
    currentAttendees: 18,
    imageUrl: "/placeholder.svg?height=200&width=300",
    organizer: {
      name: "Mindful Movement",
      email: "hello@mindfulmovement.com",
    },
    tags: ["yoga", "wellness", "morning", "outdoor"],
    featured: false,
  },
  {
    id: "7",
    title: "Cooking Class: Italian Cuisine",
    description: "Learn to make authentic Italian pasta and sauces from scratch. Includes dinner and wine pairing.",
    category: "workshop",
    date: "2024-01-26",
    time: "17:00",
    location: "Culinary Institute Downtown",
    address: "147 Chef's Row, Culinary District",
    price: 75,
    maxAttendees: 12,
    currentAttendees: 9,
    imageUrl: "/placeholder.svg?height=200&width=300",
    organizer: {
      name: "Chef Marco Rossi",
      email: "marco@culinaryinstitute.com",
    },
    tags: ["cooking", "italian", "pasta", "wine"],
    featured: true,
  },
  {
    id: "8",
    title: "Local Band Showcase",
    description:
      "Discover amazing local talent! Five bands will perform original music. Support your local music scene.",
    category: "concert",
    date: "2024-01-29",
    time: "19:30",
    location: "Underground Music Venue",
    address: "258 Rock St, Music Quarter",
    price: 18,
    maxAttendees: 150,
    currentAttendees: 72,
    imageUrl: "/placeholder.svg?height=200&width=300",
    organizer: {
      name: "Local Music Collective",
      email: "shows@localmusiccollective.com",
    },
    tags: ["local bands", "original music", "showcase"],
    featured: false,
  },
]

export const eventCategories = [
  { id: "community", name: "Community", icon: "Users", color: "bg-green-100 text-green-800" },
  { id: "sports", name: "Sports", icon: "Trophy", color: "bg-blue-100 text-blue-800" },
  { id: "workshop", name: "Workshops", icon: "BookOpen", color: "bg-purple-100 text-purple-800" },
  { id: "concert", name: "Concerts", icon: "Music", color: "bg-red-100 text-red-800" },
  { id: "performance", name: "Performances", icon: "Theater", color: "bg-yellow-100 text-yellow-800" },
]
